spring:
  application:
    name: timeline-service
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8083

app:
  aws:
    region: eu-north-1
  sqs:
    timeline-events-queue-url: ${TIMELINE_EVENTS_QUEUE_URL:https://sqs.eu-north-1.amazonaws.com/000000000000/timeline-events}
