ALTER TABLE users ADD COLUMN followers_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN following_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN posts_count INT NOT NULL DEFAULT 0;
